name: Fetch Last 10 VMESS from Telegram

on:
  workflow_dispatch:

jobs:
  fetch-vmess:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - uses: actions/checkout@v4
        with:
          persist-credentials: true

      # Setup Python 3.12
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # Install dependencies
      - name: Install Telethon
        run: |
          pip install --upgrade pip
          pip install telethon

      # Run the fetch_vmess.py script
      - name: Run fetch_vmess.py
        env:
          TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID }}
          TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
          TG_SESSION_B64: ${{ secrets.TG_SESSION_B64 }}
        run: python fetch_vmess.py

      # Commit & push results
      - name: Commit & Push Results
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add results/
          git commit -m "Update last 10 VMESS results [skip ci]" || echo "No changes to commit"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:main
